# Starter pipeline for Amazon Linux
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Amazon Linux  
  # If using a self-hosted agent, specify the agent pool name here.
  # Azure DevOps does not provide an Amazon Linux-hosted agent.

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
